name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.10
          auto-update-conda: true
          auto-activate-base: true

      - name: Reset Conda Configuration
        run: |
          conda clean --all --yes
          conda config --set always_yes true
          conda config --set changeps1 false
          conda info

      - name: Install dependencies
        run: |
          conda install -y pandas matplotlib seaborn scikit-learn flake8 pytest notebook


