name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.10
          activate-environment: base

      - name: Install dependencies
        run: |
          conda install -y pandas matplotlib seaborn scikit-learn flake8 pytest notebook

      - name: Verify `clean_data.py`
        run: |
          python clean_data.py

      - name: Run clustering notebook
        run: |
          conda install -y -c conda-forge papermill
          papermill clustering.ipynb clustering_output.ipynb

      - name: Run exploration notebook
        run: |
          papermill exploration.ipynb exploration_output.ipynb

      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Test with pytest
        run: |
          pytest

